repos:
  - repo: https://github.com/troian/pre-commit-golang
    rev: ab57c5db44bbeeae1031a2e9c2889367f8387d59
    hooks:
      - id: go-fmt
      - id: go-build
  - repo: https://github.com/Bahjat/pre-commit-golang
    rev: c3086eea8af86847dbdff2e46b85a5fe3c9d9656
    hooks:
      - id: go-fmt-import
      - id: go-vet
      - id: go-unit-tests
      - id: gofumpt # requires github.com/mvdan/gofumpt
      - id: golangci-lint # requires github.com/golangci/golangci-lint